"""empty message

Revision ID: 64e113cf2eda
Revises: dd7048b792f3
Create Date: 2020-01-19 19:13:09.429191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64e113cf2eda'
down_revision = 'dd7048b792f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('products', sa.Column('category', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'category', ['category'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'category')
    op.drop_table('category')
    # ### end Alembic commands ###
