"""empty message

Revision ID: dd7048b792f3
Revises: 91acaa635138
Create Date: 2020-01-09 07:12:45.289655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd7048b792f3'
down_revision = '91acaa635138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('Additional_information', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'Additional_information')
    # ### end Alembic commands ###
